### PR TITLE
Suggestions to remove this

### LINKED ISSUE #225: unable to update quantity and units.
commands like 
update 1 --q 2,
update 2 --q 2 --u packet

does not work

### PR DESCRIPTION
**Pull request by wanjuin**

### CODE REVIEW

**Comment by wanjuin** [comment]
After removing these lines, everything will work as intended.
image

File: src/main/java/seedu/duke/commands/UpdateCommand.java [hunk 1]
```diff
@@ -56,9 +56,6 @@ private void updateFoodAttribute(Food currentFood, String flagName, String flagV
                 currentFood.setExpiryDate(flagValue);
                 break;
             case "q":
-                if (currentFood.getQuantity() == 0 && !Arrays.asList(flags).contains("u")) {
-                    throw new DukeException("Please set the unit to change a quantity");
-                }
```
Comment (DavidVin357) [inline src/main/java/seedu/duke/commands/UpdateCommand.java:61]: Thanks @wanjuin! Just wanted to fix that :)

**Review by DavidVin357 — APPROVED** [review]
